from typing import Any, Dict, List, Optional
from agents.base_agent import BaseAgent, AgentResponse
from core.schema import Task, TaskStatus, Artifact, ArtifactType, FilePatch
from core.gemini_client import GeminiClient
from core.prompts import DEBUG_PATCH_PROMPT
import json
import os

class DebugAgent(BaseAgent):
    def __init__(self, name: str = "Debug", role: str = "Senior Diagnostic & Repair Engineer"):
        super().__init__(name, role)
        self.client = GeminiClient()

    async def execute(self, task: Task, context: Optional[Dict[str, Any]] = None) -> AgentResponse:
        self.log(f"DebugAgent analyzing failure for: {task.description}")
        
        target_path = task.input_data.get("path") or getattr(task, "artifact_path", "")
        if not target_path:
            return AgentResponse(
                agent_name=self.name,
                status=TaskStatus.FAILED,
                output={"error": "DebugAgent requires an artifact path to analyze."},
                logs=["No target path provided to DebugAgent."]
            )

        broken_code = ""
        project_path = context.get("project_path", "") if context else ""
        full_path = os.path.join(project_path, target_path)
        
        if os.path.exists(full_path):
            with open(full_path, "r") as f:
                broken_code = f.read()
        else:
            self.log(f"Warning: File not found at {full_path}. Proceeding with empty context.", "warning")

        # Traceback enhancement
        from core.traceback_analyzer import TracebackAnalyzer
        repair_instructions = getattr(task, "repair_instructions", "Unknown")
        analysis = TracebackAnalyzer.analyze(repair_instructions, "")
        
        enhanced_instructions = repair_instructions
        if analysis.is_syntax_error or analysis.root_cause != "runtime_crash":
             enhanced_instructions += f"\n[AUTO-ANALYSIS] Root Cause: {analysis.root_cause}. Suggestion: {analysis.suggested_fix}"
             if analysis.line_number:
                 enhanced_instructions += f"\n[AUTO-ANALYSIS] Focus on Line: {analysis.line_number}"

        mem = context.get("memory", {}) if context else {}
        failed_patches = mem.get("failed_patches", {}).get(target_path, [])
        if failed_patches:
            enhanced_instructions += "\n\n[ANTI-LOOP MEMORY] You have previously attempted the following patches which DID NOT resolve the issue. DO NOT suggest these exact patches again:\n"
            for idx, fp in enumerate(failed_patches):
                reason = fp.get('reason', 'Applied but failed validation/runtime')
                enhanced_instructions += f"--- Failed Attempt {idx+1} | {reason} ---\nReplaced:\n{fp.get('search_block')}\n\nWith:\n{fp.get('replace_block')}\n\n"

        prompt = DEBUG_PATCH_PROMPT.format(
            path=target_path,
            failing_check=getattr(task, "failing_check", "Validation failure"),
            repair_reason=getattr(task, "repair_reason", "Unknown"),
            repair_instructions=enhanced_instructions,
            context=json.dumps(context or {}, default=str),
            broken_code=broken_code
        )
        
        try:
            raw_response = await self.client.generate_content(prompt)
            data = json.loads(raw_response)
            
            patches_data = data.get("patches", [])
            if not patches_data:
                self.log("DebugAgent did not return any patches.", "warning")
            
            # Formulate the response artifact structure
            artifact = Artifact(
                task_id=task.id,
                path=target_path,
                artifact_type=ArtifactType.PATCH,
                content="", # Patches don't replace the whole content inherently in the artifact struct, but we use the patches array
                patches=[FilePatch(**p) for p in patches_data],
                metadata={
                    "language": "diff",
                    "explanation": "Patches generated by DebugAgent"
                }
            )
            
            self.log(f"Successfully generated {len(patches_data)} patches for {target_path}")
            return AgentResponse(
                agent_name=self.name,
                status=TaskStatus.COMPLETED,
                output={"artifacts": [artifact.model_dump()]},
                logs=[f"DebugAgent emitted patches for {target_path}."]
            )

        except Exception as e:
            self.log(f"DebugAgent Generation Error: {str(e)}", "error")
            return AgentResponse(
                agent_name=self.name,
                status=TaskStatus.FAILED,
                output={"error": str(e)},
                logs=[f"FAILED to generate patches: {str(e)}"]
            )
