from typing import Any, Dict, List, Optional
from agents.base_agent import BaseAgent, AgentResponse
from core.schema import Task, TaskStatus, TaskPriority, GoalState
from core.gemini_client import GeminiClient
from core.prompts import PLANNER_PROMPT_TEMPLATE
import json
import uuid

class PlannerAgent(BaseAgent):
    def __init__(self, name: str = "Planner", role: str = "System Architect & Task Planner"):
        super().__init__(name, role)
        self.client = GeminiClient()
        self.memory_context: List[Dict[str, Any]] = []

    async def execute(self, goal_description: str, context: Optional[Dict[str, Any]] = None) -> AgentResponse:
        """
        Uses Gemini to generate a structured GoalState from a natural language goal.
        """
        self.log(f"Brainstorming plan for: {goal_description}")
        
        mem_ctx = context.get("memory", {}) if context else {}
        prompt = PLANNER_PROMPT_TEMPLATE.format(
            goal=goal_description,
            memory=json.dumps(mem_ctx, default=str)
        )
        
        retries = 3
        last_error = None
        
        while retries > 0:
            try:
                raw_response = await self.client.generate_content(prompt)
                plan_data = json.loads(raw_response)
                
                # Validation & Parsing
                goal_id = str(uuid.uuid4())
                processed_tasks = {}
                
                for t_id, t_info in plan_data.get("tasks", {}).items():
                    # Map priority to Enum
                    priority_val = t_info.get("priority", 2)
                    priority = TaskPriority(priority_val) if priority_val in [1,2,3,4] else TaskPriority.MEDIUM
                    
                    processed_tasks[t_id] = Task(
                        goal_id=goal_id,
                        agent_type=t_info.get("agent_type"),
                        task_type=t_info.get("task_type"),
                        description=t_info.get("description"),
                        priority=priority,
                        dependencies=t_info.get("dependencies", []),
                        input_data=t_info.get("input_data", {})
                    )
                
                if not processed_tasks:
                    raise ValueError("No tasks generated by LLM.")

                goal_state = GoalState(
                    goal_id=goal_id,
                    original_goal=goal_description,
                    tasks=processed_tasks
                )
                
                # Store in memory context
                self.memory_context.append({
                    "goal": goal_description,
                    "goal_id": goal_id,
                    "task_count": len(processed_tasks)
                })
                
                self.log(f"Plan generated successfully with {len(processed_tasks)} tasks.")
                
                # Band Integration
                try:
                    from core.band_service import band_service
                    import asyncio
                    asyncio.create_task(band_service.publish_planner_summary(goal_state))
                except Exception as e:
                    self.log(f"Band Integration Error: {str(e)}", "warning")
                
                return AgentResponse(
                    agent_name=self.name,
                    status=TaskStatus.COMPLETED,
                    output=goal_state,
                    logs=[f"Gemini successfully mapped goal to {len(processed_tasks)} tasks."]
                )

            except json.JSONDecodeError as e:
                self.log(f"Parsing failure (retries left: {retries-1}): {str(e)}", "warning")
                last_error = e
            except Exception as e:
                self.log(f"Execution error (retries left: {retries-1}): {str(e)}", "error")
                last_error = e
                
            retries -= 1
            
        return AgentResponse(
            agent_name=self.name,
            status=TaskStatus.FAILED,
            output={"error": f"Failed to generate valid plan after multiple retries. Last error: {str(last_error)}"},
            logs=[f"PLANNER FAILURE: {str(last_error)}"]
        )
